### ISSUE TITLE
Throw exception when there is a keyUp event

### ISSUE THREAD

**Issue by izissise** [carmebar/unicornpass#1]
Hello, 
when I press a key while not being in a input box unicornpass throw an exception.
<img width="1168" alt="unicprnpass" src="https://cloud.githubusercontent.com/assets/2104672/12407715/995cc4aa-be0e-11e5-8aa2-20cff22f353a.png">
It's a little annoying when using the webconsole as it stop javascript.

**Comment by carmebar** [comment]
Thank you for posting the issue.
I think it's now fixed, could you please check with the new XPI (0.1.2) before I mark it as fixed and upload the new version to the Add-ons store?
Edit: Was able to reproduce and check myself.

Thank you again!

**Comment by izissise** [comment]
Great thanks !!
