### ISSUE TITLE
Use SHA512 instead of SHA1

### ISSUE THREAD

**Issue by emersion** [carmebar/unicornpass#3]
SHA1 is weak and shouldn't be used anymore. Use SHA512 instead.

Note: I created [a unicornpass library for Node and browsers](https://github.com/emersion/node-unicornpass), which is using SHA512. It could be cool to just `require()` it. ;-)

**Comment by carmebar** [comment]
Sorry for taking so long to address this issue.

SHA1 is good enough for this purpose, even md5 would be good. Can you express what thread model do you have in mind in which the use of SHA1 weakens the security?

Won't fix for now. Glad to see you liked the idea and made a module yourself :smile:
