### ISSUE TITLE
Not compatible with multiprocess

### ISSUE THREAD

**Issue by roidelapluie** [carmebar/unicornpass#4]
This addon is not compatible with multiprocess :(

**Comment by roidelapluie** [comment]
https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/

**Comment by carmebar** [comment]
Thanks for letting me know. I'll fix it later today :smile:

**Comment by carmebar** [comment]
I've marked the extension as multiprocess compatible and tested it on Firefox Developer Edition with e10s enabled. I'll be uploading it to AMO later.
Should be working fine now :+1:

**Comment by roidelapluie** [comment]
Thanks!
