### ISSUE TITLE
Addon shown as «legacy»

### ISSUE THREAD

**Issue by leplatrem** [carmebar/unicornpass#6]
![screenshot from 2017-08-03 10-23-55](https://user-images.githubusercontent.com/546692/28912770-e55df710-7835-11e7-8b76-96155a7f38d7.png)

Would switching to Web Extensions require a lot of work ? Do you need help ?

**Comment by carmebar** [comment]
I will upgrade the extension. Thanks for reminding me 😄

**Comment by carmebar** [comment]
I've created a web-extension branch with the working add-on. I'll test in on Chrome and Opera and upgrade on AMO soon.

If you're able to test the web-extension branch I'd really appreciate it. Cheers!

**Comment by leplatrem** [comment]
Seems to work like a charm:

Only tested with:
* Firefox nightly
* Load temporary addon from `about:debugging`
* Opened private window to open some login form
* Checked that no *Legacy* label is shown in `about:addons`

Well done! Thanks for your cool addon!

**Comment by carmebar** [comment]
Added the updated version for review at AMO and merged the branch.

Thanks for raising the issue. Take care 😃
